swagger: "2.0"
info:
  title: hwp-manager
  description: hwp-manager test
  version: 0.0.1
#host: localhost:3002
schemes:
  - http
  - https

tags:
  - name: work
    description: 문제 처리 포맷입니다.

securityDefinitions:
  jwt:
    type: "basic"

  bearer:
    type: apiKey
    name: Authorization
    in: header

security:
  - jwt: []
  - bearer: []

paths:
  /question/hwpMetadataExtract:
    post:
      summary: "개의 소리를 분석합니다."
      description: "bark, growling, howling, whining 4가지의 class"

      tags:
        - process
      parameters:
#        - name: body
#          in: body
#          required: true
#          schema:
#            properties:
#              workGroupId:
#                type: string

      responses:
        200:
          description: "workKey를 내려줍니다."
          schema:
            properties:
              workKey:
                type: string
        400:
          description: "Bad Request : 요청이 잘못되었습니다."
        404:
          description: "Not Found : S3에 파일이 없습니다."
        500:
          description: "Unexpected Exception : 알 수 없는 에러입니다."